# Config dedicated for module A
# All the resources must be prefixed with `module-a-` to avoid conflicts

version: 2.1

parameters:
  module-a-terraform-workflow:
    type: string
    default: ""

jobs:
  plan:
    description:
      Generates TF plan for a TF configuration in the specified directory
      and saves that into a workspace.
    parameters:
      working_directory:
        description: Root directory of the Terraform configuration.
        type: string
    docker:
      - image: hashicorp/terraform:1.3.7
    steps:
      - checkout
      - run:
          name: terraform initializing
          command: |
            terraform init -input=false
          working_directory: << parameters.working_directory >>
      - run:
          name: terraform plan
          command: terraform plan -out tfapply
          working_directory: << parameters.working_directory >>
      - persist_to_workspace:
          root: << parameters.working_directory >>
          paths:
            - .
  apply:
    description: Applies a TF plan saved in the workspace previously by the plan job.
    parameters:
      working_directory:
        description: Root directory of the Terraform configuration.
        type: string
    docker:
      - image: hashicorp/terraform:1.3.7
    steps:
      - checkout
      - attach_workspace:
          at: << parameters.working_directory >>
      - run:
          name: terraform apply
          command: terraform apply -auto-approve tfapply
          working_directory: << parameters.working_directory >>

workflows:
  module-a-terraform-workflow:
    jobs:
      - plan:
          context: aws-access
          working_directory: "/module-a"
      - hold:
          type: approval
          requires:
            - plan
      - apply:
          context: aws-access
          working_directory: "/module-a"
          requires:
            - hold
